language: go
go:
  - 1.9.x
  - 1.10.x
  - tip
services:
  - mysql
  - postgresql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unixodbc unixodbc-dev
  - go get github.com/mattn/goveralls golang.org/x/vgo
install:
  - ./contrib/grab-oracle.sh
  - export PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/instantclient_12_1
script:
  - vgo build -tags 'all icu fts5 vtable json1 no_ql'
  - vgo test -tags 'all no_ql' -v ./stmt
